"""Pydantic schema 集合。"""
from matrix.api.schemas.account import (
    Account,
    AccountCreate,
    AccountListResponse,
    AccountUpdate,
)
from matrix.api.schemas.business import (
    Business,
    BusinessCreate,
    BusinessListResponse,
    BusinessStatus,
    BusinessUpdate,
)
from matrix.api.schemas.device import (
    Device,
    DeviceListResponse,
    DevicePairRequest,
    DevicePairResponse,
    DeviceRegisterRequest,
    DeviceRetireResponse,
    DeviceUnbindResponse,  # 兼容旧名
    DeviceUpdate,
)
from matrix.api.schemas.agent_run import AgentRun, AgentRunListResponse
from matrix.api.schemas.alerts import (
    AlertItem,
    AlertListResponse,
    AlertResolveRequest,
    AlertResolveResponse,
    AlertSeverity,
)
from matrix.api.schemas.analytics import (
    AccountContentStats,
    AccountContentStatsResponse,
    BusinessComparisonResponse,
    BusinessComparisonRow,
)
from matrix.api.schemas.chat import (
    ChatAction,
    ChatActionType,
    ChatHistoryMessage,
    ChatRequest,
    ChatResponse,
)
from matrix.api.schemas.goal import (
    Goal,
    GoalCreate,
    GoalUpdate,
    GoalListResponse,
    GoalPhase,
    GoalRound,
    GoalRoundListResponse,
    GoalType,
    ThemeTarget,
)
from matrix.api.schemas.health import ErrorDetail, ErrorResponse, Health, OkResponse
from matrix.api.schemas.interaction import (
    Interaction,
    InteractionListResponse,
    InteractionResult,
    InteractionType,
)
from matrix.api.schemas.kb import (
    KbDocument,
    KbDocumentCreate,
    KbDocumentListResponse,
    KbDocumentUpdate,
    KbPublishRequest,
    KbPublishResponse,
    KbSearchHit,
    KbSearchRequest,
    KbSearchResponse,
    KbType,
    ViralIngestRequest,
    ViralIngestResponse,
)
from matrix.api.schemas.note import Note, NoteCreate, NoteListResponse, NoteUpdate
from matrix.api.schemas.notification import (
    NotificationItem,
    NotificationListResponse,
    NotificationMarkReadRequest,
    NotificationMarkReadResponse,
    NotificationSeverity,
)
from matrix.api.schemas.persona import (
    Persona,
    PersonaCreate,
    PersonaListResponse,
    PersonaUpdate,
)
from matrix.api.schemas.settings import AppSetting, AppSettingList, AppSettingUpsert

__all__ = [
    "Account",
    "AccountCreate",
    "AccountListResponse",
    "AccountUpdate",
    "Business",
    "BusinessCreate",
    "BusinessListResponse",
    "BusinessStatus",
    "BusinessUpdate",
    "AccountContentStats",
    "AccountContentStatsResponse",
    "AgentRun",
    "BusinessComparisonResponse",
    "BusinessComparisonRow",
    "AgentRunListResponse",
    "AlertItem",
    "AlertListResponse",
    "AlertResolveRequest",
    "AlertResolveResponse",
    "AlertSeverity",
    "ChatAction",
    "ChatActionType",
    "ChatHistoryMessage",
    "ChatRequest",
    "ChatResponse",
    "Device",
    "DeviceListResponse",
    "DevicePairRequest",
    "DevicePairResponse",
    "DeviceRegisterRequest",
    "DeviceRetireResponse",
    "DeviceUnbindResponse",  # 兼容旧名
    "DeviceUpdate",
    "ErrorDetail",
    "ErrorResponse",
    "Goal",
    "GoalCreate",
    "GoalUpdate",
    "GoalListResponse",
    "GoalPhase",
    "GoalRound",
    "GoalRoundListResponse",
    "GoalType",
    "Health",
    "Interaction",
    "InteractionListResponse",
    "InteractionResult",
    "InteractionType",
    "KbDocument",
    "KbDocumentCreate",
    "KbDocumentListResponse",
    "KbDocumentUpdate",
    "KbPublishRequest",
    "KbPublishResponse",
    "KbSearchHit",
    "KbSearchRequest",
    "KbSearchResponse",
    "KbType",
    "ViralIngestRequest",
    "ViralIngestResponse",
    "Note",
    "NoteCreate",
    "NoteListResponse",
    "NoteUpdate",
    "NotificationItem",
    "NotificationListResponse",
    "NotificationMarkReadRequest",
    "NotificationMarkReadResponse",
    "NotificationSeverity",
    "OkResponse",
    "Persona",
    "PersonaCreate",
    "PersonaListResponse",
    "PersonaUpdate",
    "AppSetting",
    "AppSettingList",
    "AppSettingUpsert",
    "ThemeTarget",
]
